import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131316',
        'surface': '#131316',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'surface-bright': '#39393c',
        'surface-variant': '#353438',
        'on-surface': '#e5e1e6',
        'on-surface-variant': '#dfbfbd',
        'on-background': '#e5e1e6',
        'background': '#131316',
        'primary': '#ffb3af',
        'primary-container': '#b84040',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3af',
        'on-primary': '#68010e',
        'on-primary-container': '#ffe4e2',
        'on-primary-fixed': '#410005',
        'on-primary-fixed-variant': '#881d21',
        'inverse-primary': '#a93536',
        'secondary': '#a9c9f1',
        'secondary-container': '#2a4b6c',
        'secondary-fixed': '#d0e4ff',
        'secondary-fixed-dim': '#a9c9f1',
        'on-secondary': '#0c3252',
        'on-secondary-container': '#9bbbe2',
        'on-secondary-fixed': '#001d35',
        'on-secondary-fixed-variant': '#28496a',
        'tertiary': '#7cd7c2',
        'tertiary-container': '#007766',
        'tertiary-fixed': '#98f3de',
        'tertiary-fixed-dim': '#7cd7c2',
        'on-tertiary': '#00382f',
        'on-tertiary-container': '#9ffbe5',
        'on-tertiary-fixed': '#00201a',
        'on-tertiary-fixed-variant': '#005144',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#a68a88',
        'outline-variant': '#584140',
        'inverse-surface': '#e5e1e6',
        'inverse-on-surface': '#303033',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
